<?php

declare(strict_types=1);

namespace App\Constants;

class Events
{
    public const CLICK_CHECKOUT_BUTTON = 'CLICK_CHECKOUT_BUTTON';

    public const MIDDLEWARE_VALIDATE_TOKEN_INITIALIZE = 'MIDDLEWARE_VALIDATE_TOKEN_INITIALIZE';
    public const MIDDLEWARE_VALIDATE_TOKEN_ERROR = 'MIDDLEWARE_VALIDATE_TOKEN_ERROR';
    public const MIDDLEWARE_VALIDATE_TOKEN_FINALIZE = 'MIDDLEWARE_VALIDATE_TOKEN_FINALIZE';

    public const CONTROLLER_INIT_ORDER_ERROR = 'CONTROLLER_INIT_ORDER_ERROR';
    public const CONTROLLER_INIT_ORDER_INITIALIZE = 'CONTROLLER_INIT_ORDER_INITIALIZE';
    public const CONTROLLER_INIT_ORDER_INIT_ENDPOINT_CALLED = 'CONTROLLER_INIT_ORDER_INIT_ENDPOINT_CALLED';
    public const CONTROLLER_INIT_ORDER_INIT_ENDPOINT_RESPONDED = 'CONTROLLER_INIT_ORDER_INIT_ENDPOINT_RESPONDED';
    public const CONTROLLER_INIT_ORDER_FINALIZE = 'CONTROLLER_INIT_ORDER_FINALIZE';

    public const CONTROLLER_RESUME_ORDER_ERROR = 'CONTROLLER_RESUME_ORDER_ERROR';
    public const CONTROLLER_RESUME_ORDER_INITIALIZE = 'CONTROLLER_RESUME_ORDER_INITIALIZE';
    public const CONTROLLER_RESUME_ORDER_RESUME_ENDPOINT_CALLED = 'CONTROLLER_RESUME_ORDER_RESUME_ENDPOINT_CALLED';
    public const CONTROLLER_RESUME_ORDER_RESUME_ENDPOINT_RESPONDED = 'CONTROLLER_RESUME_ORDER_RESUME_ENDPOINT_RESPONDED';
    public const CONTROLLER_RESUME_ORDER_FINALIZE = 'CONTROLLER_RESUME_ORDER_FINALIZE';
}
